In [3]:
from cylp.cy.CyClpSimplex import CyClpSimplex
from cylp.py.modeling.CyLPModel import CyLPArray
import numpy as np
s = CyClpSimplex()
x = s.addVariable('x', 2)
# Create coefficients and bounds
A = np.matrix([[-1, 1]])
a = CyLPArray([1])
# Add constraints
s += A * x <= a
s += 2 <= B * x + D * y <= b
s += y >= 0
s += 1.1 <= x[1:3] <= x_u

# Set the objective function
c = CyLPArray([1., -2., 3.])
s.objective = c * x + 2 * y.sum()
s.maxNumIteration = 1

## cylp and pulp translation

`LpStatus[prob.status]` : `s.getStatusString()`
: `dict([(i, s.primalVariableSolution['x'][i]) for i in range(len(OBJ))])`


In [5]:
s.initialDualSolve()

'stopped on iterations or time'

In [6]:
s.maxNumIteration

1

In [6]:
from coinor.grumpy import GenerateRandomMIP
import numpy as np
from cylp.cy.CyClpSimplex import CyClpSimplex
from cylp.py.modeling.CyLPModel import CyLPModel, CyLPArray
CONSTRAINTS, VARIABLES, OBJ, MAT, RHS = GenerateRandomMIP(numVars=2, numCons=5, density=0.1,rand_seed=1234)
model = CyLPModel()
x = model.addVariable('x', dim=len(OBJ))
cyOBJ = CyLPArray([-val for val in OBJ.values()])
cyMAT = np.matrix([MAT[v] for v in VARIABLES]).T
cyRHS = CyLPArray(RHS)
model += cyMAT * x <= RHS
model += 0 <= x <= 1
model.objective = cyOBJ * x
s = CyClpSimplex(model)
# s.primal()


In [7]:
s.primal()

'optimal'

In [8]:
s.getStatusCode(), s.getStatusString()

(0, 'optimal')

In [14]:
s.getStatusString() == "dual infeasible"

True

In [17]:
s.primalVariableSolution['x']

array([0.1, 1. ])

{0: 0.1, 1: 0.9999999999999999}

In [2]:
s.variablesLower, s.variablesUpper

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

In [5]:
s.dual()

'dual infeasible'

In [27]:
from cylp.cy.CyClpSimplex import CyClpSimplex
from cylp.py.modeling.CyLPModel import CyLPArray
import numpy as np
s = CyClpSimplex()
x = s.addVariable('x', 2)

# Create coefficients and bounds
A = np.matrix([[1,1],[0,1]])
a = CyLPArray([5,3])


# Add constraints
s += A * x >= a


# Set the objective function
c = CyLPArray([1,1])
s.objective = c*x
print(s.initialDualSolve())
print(s.primal())
print(s.objectiveValue)
print(s.primalVariableSolution)

optimal
optimal
5.0
{'x': array([2., 3.])}
